### ISSUE TITLE
BUG: The "All projects" placeholder in the project selector on the dashboard is not cleared when active 

### ISSUE THREAD

**Issue by ThatGalNatalie** [PrefectHQ/ui#1008]
**Bug Description**

In the project selector on the dashboard, when trying to search for a project, the "All projects" placeholder is not cleared  when clicked on in Safari

**Steps To Reproduce**

1. Open Safari
2. Go to the dashboard
3. Go to the project selector and click on "All projects" 
4. Type for a project and "all projects" should have been cleared but is now incorporated with whatever you typed

**Browsers Tested:**
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Edge
* [ ] IE

----------
**Notes**
On Safari:
https://user-images.githubusercontent.com/40726391/131721590-8e9045d3-3039-477f-aa05-b336b235d88d.mov

On Firefox:
https://user-images.githubusercontent.com/40726391/131721658-85cd1d4b-eee2-42ca-826f-03eaa6732225.mov

**Comment by znicholasbrown** [comment]
@ThatGalNatalie is this a bug? I think `All Projects` is a valid selection here (and is searchable as well)

**Comment by ThatGalNatalie** [comment]
> @ThatGalNatalie is this a bug? I think `All Projects` is a valid selection here (and is searchable as well)

Now thinking about it, I don't think this is a bug but maybe an enhancement? Or should we just close this?

**Comment by zhen0** [comment]
Closing for now since we don't think it's a bug.
