### ISSUE TITLE
BUG: ECSRun on Run Screen breaks if `run_task_kwargs` are not provided

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/ui#1023]
**Bug Description**

If you don't provide `run_task_kwargs` when customizing a Run Config on the Run screen, the flow errors out with
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "null", must be one of: capacityProviderStrategy, cluster, count, enableECSManagedTags, enableExecuteCommand, group, launchType, networkConfiguration, overrides, placementConstraints, placementStrategy, platformVersion, propagateTags, referenceId, startedBy, tags, taskDefinition
```

This is because when no key / value pairs are provided for `run_task_kwargs`, it seems the UI submits `{"null": null}` as the key / value pair:
```json
"run_task_kwargs": {"null": null}
```
when instead it should submit 
```json
"run_task_kwargs": null
```

**Steps To Reproduce**

1. Start an ECS agent
2. Navigate to "Run" screen on any flow page
3. Set the appropriate labels for the ECS agent
4. provide a valid `task_role_arn`
5. Run -- you'll see the above incorrect run task dict in the backend, and the run will error out with the error above

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

The UI should submit `null` if no values are provided for `run_task_kwargs` **cc:** @kmoonwright

**Comment by znicholasbrown** [comment]
@cicdw since `run_task_kwargs` is a dict, an empty dict is valid as well, correct? #1029 fixes the issue where the dict was being sent as `{ "null": null }`but a further update to the run component would be needed to filter out dict type fields that have no key/values and set them to null instead of an empty object/dict.
