### ISSUE TITLE
BUG: Interacting with the JSON parameter box freezes the UI

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/ui#1077]
**Bug Description**

Whenever I open the JSON editor for parameters, my browser freezes, sometimes for a while (up to about a minute or so), and causes Chrome to ask me if I want to exit the page. Usually, the page recovers.

**Steps To Reproduce**

1. Go to a Flow with parameters
2. Click on the Run tab
3. Switch on the JSON parameters
4. Make any change (but especially copy/paste in a whole JSON object)
5. Observe freeze/lack of interactivity

**Browsers Tested:**
* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

It doesn't show in the LogRocket session since I think we stop sending events, but here it is: https://app.logrocket.com/qetfiw/cloud-web-ui/s/5-5569b09d-db1e-4588-9c3b-8c846f7e6fd3/1?filters=%255B%257B%2522id%2522%253A%2522S1ZsA5nNY%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522contains%2522%252C%2522type%2522%253A%2522CONTAINS%2522%252C%2522hasStrings%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522dylan%2540prefect.io%2522%255D%257D%255D&fromTab=latest

**Comment by zhen0** [comment]
@stackoverfloweth - this could be a useful one for you?

**Comment by stackoverfloweth** [comment]
should be closed with #1095 merged?

**Comment by dylanbhughes** [comment]
LGTM
