### ISSUE TITLE
BUG: SKIPPED states don't have end times so UI counts up duration forever

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/ui#1110]
**Bug Description**

![Screen Shot 2021-11-03 at 5 15 57 PM](https://user-images.githubusercontent.com/2325367/140194073-4a92e301-caa0-42ec-99b5-3ad2c9b47584.png)

**Steps To Reproduce**

1. Get a task run to raise a `SKIP` signal
2. Go to the Task Run page in the UI or the mapped runs page
3. Watch the duration count slowly upwards forever

**Browsers Tested:**
* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by zhen0** [comment]
Looks like a similar issues to https://github.com/PrefectHQ/prefect/issues/4864 - we can likely use a similar fix as we did for tooltips in https://github.com/PrefectHQ/ui/pull/1030
