### ISSUE TITLE
Improve Agent Automations UX 

### ISSUE THREAD

**Issue by joeclayallday** [PrefectHQ/ui#1113]
**Why**
As a user, when I make Agent Automations the installation instructions could be shown more obviously and I'd like to not leave the automations page to copy the agent-config-id (currently I have to leave and ping graphQL for agent-config-ids).

**What**
• After creating an agent config, allow users to simply copy the newly created agent-config-ids in the UI.
• Add clear text instructions that inform users how to install these agent automations at registration in the Prefect CLI & that if agents share agent-config-ids, then the automations doesn't work until all agents go unhealthy instead of individually.
• This proposal doesn't change any application behavior, only front-end tweaks.

**Notes**
Proposed in-app messaging:

To set up an agent automation, you need to add the agent-config-id flag at agent registration.
If you attach the same ID to multiple agents, Prefect will only notify you if all agents are unhealthy.

**BEFORE**
<img width="861" alt="Screen Shot 2021-11-05 at 5 10 47 PM" src="https://user-images.githubusercontent.com/4295811/140584126-f76966f9-8f17-4ddf-9497-5fa7fe286de1.png">

**AFTER**
<img width="859" alt="Screen Shot 2021-11-05 at 5 10 50 PM" src="https://user-images.githubusercontent.com/4295811/140584139-013eb803-371f-4f88-b6a2-49adcc95037c.png">

**NOTE:** On Create Success Modal, reveal agent-config-id

<img width="1125" alt="Screen Shot 2021-11-05 at 7 55 26 PM" src="https://user-images.githubusercontent.com/4295811/140592494-bfbeee9e-7010-4e72-84b8-60c69f2e330b.png">

<img width="857" alt="Screen Shot 2021-11-05 at 5 10 55 PM" src="https://user-images.githubusercontent.com/4295811/140584148-eeb9e1e2-6c95-4e59-a129-5dfe496f5c93.png">

<img width="824" alt="Screen Shot 2021-11-05 at 5 10 59 PM" src="https://user-images.githubusercontent.com/4295811/140584154-474df2d2-ab69-4bac-88d6-2444e06bd4da.png">

<img width="816" alt="Screen Shot 2021-11-05 at 5 11 02 PM" src="https://user-images.githubusercontent.com/4295811/140584161-e5fe0de9-1b59-4c80-b90e-9c5a239b903d.png">

**Comment by zhen0** [comment]
Thanks @joeclayallday - For info (mainly if any users stumble across this before we get changes released) - the UI does currently show agent config IDs without a user needing to use a graphQL query or the API.  They're shown by hovering over the info button:

<img width="978" alt="Screen Shot 2021-11-08 at 4 46 44 PM" src="https://user-images.githubusercontent.com/40272060/140823349-8d0f3bcd-30c6-4868-9106-5af242ee8f20.png">
<img width="1005" alt="Screen Shot 2021-11-08 at 4 38 48 PM" src="https://user-images.githubusercontent.com/40272060/140823205-a6439310-da21-4e3e-b456-c3915caf784a.png">
