### ISSUE TITLE
BUG: Remove automations tab from flow page on Server

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/ui#1168]
**Bug Description**

**Steps To Reproduce**

1. 

**Browsers Tested:**
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by szczeles** [comment]
Also, it the link to Automation Actions should be hidden from Team menu on Server, as the view doesn't work.

It makes a request that fails on Server setup with:

```
  {
    "errors": [
      {
        "message": "Cannot query field \"action\" on type \"Query\".",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED"
        }
      }
    ]
  }
```

**Comment by zhen0** [comment]
Thanks @szczeles!
