### ISSUE TITLE
BUG: Misleading banner in the Calendar view

### ISSUE THREAD

**Issue by szczeles** [PrefectHQ/ui#1178]
**Bug Description**

When Calendar view is opened, there is a yellow banner "Reminder! The Prefect Scheduler will only schedule 10 runs in advance.":
https://github.com/PrefectHQ/ui/blob/89735d25de76377575c86e94c25774e644faafef/src/pages/Calendar/Calendar-Day.vue#L270

This is not true, if the `max_scheduled_runs_per_flow` flag is modified in towel, see: https://github.com/PrefectHQ/server/pull/281 - it's better to either hide the "warning" or expose the value so UI can access it and use in the banner.

**Steps To Reproduce**
1. Run Prefect Server with modified flag `max_scheduled_runs_per_flow` in towel to 24
2. Create a simple flow and schedule hourly
3. Run UI and go to Calendar view
4. The message will be displayed that only 10 runs are visible, but 24 runs will be visible in the calendar

**Browsers Tested:**
* [ ] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by zhen0** [comment]
Good flag @szczeles!  We could hide this warning for users on Server.
