### ISSUE TITLE
The flow run page shows an issue with label even though the agent is healthy (latency issue)

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/ui#1182]
The flow run page shows an issue with a label for a short while, but as soon as we hover over the red icon, it disappears. 

![ui_issue_2](https://user-images.githubusercontent.com/86264395/147145094-f43c726b-570e-46f6-9de2-bd7889597824.gif)

**Comment by zyzil** [comment]
FYI, I believe I've seen this same issue; however, it manifested itself on the dashboard page in the agent widget showing an error status that my agent has not been queried recently. Given a few seconds it will correct itself. This has happened to me at least a dozen times. Sorry I don't have a screenshot of the error condition currently, but this is the section I'm talking about:
![image](https://user-images.githubusercontent.com/3661304/147159777-14980b4f-cd6a-4ec0-9b42-5a786b7a7a3d.png)
