### ISSUE TITLE
BUG: Footer overlaps content

### ISSUE THREAD

**Issue by cdeil** [PrefectHQ/ui#1194]
If I scroll to the bottom at https://cloud.prefect.io/admin/account the footer overlaps the page content.
This is with latest Chrome on MacOS

Screenshot:

<img width="1341" alt="Screenshot 2022-01-01 at 21 55 51" src="https://user-images.githubusercontent.com/852409/147860045-983ea505-5b38-4f3b-ac83-8c84dc34af04.png">

**Comment by zhen0** [comment]
Thanks for reporting this cdeil. This also seems to be happening on the notifications page:
<img width="1326" alt="Screen Shot 2022-01-13 at 4 17 57 PM" src="https://user-images.githubusercontent.com/40272060/149410629-5aa30c18-b58b-4b70-ac80-95445e1763d6.png">

**Comment by ThatGalNatalie** [comment]
Hi @cdeil, @zhen0 and I tried to replicate this but were unable to. Were there any specific steps you took to find the bug?

**Comment by cdeil** [comment]
It was just a normal window with the URL and bug as shown in the screenshot.
Can't reproduce either now.
Closing.
