### ISSUE TITLE
Update: Change the wording on the teams page to redirect Free tier users to the plans page & Standard tier users to sales

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/ui#1208]
**Why**

- The invite members page currently tells users to contact sales if they need to add more users.  However Free tier users do not need to contact sales and should use self serve to update.  Standard tier + users will still need to contact sales. 
**What**

* [ ] Check for license level
* [ ] Add a note and link directing free/starter tier users (who have only 1 user) to the plans page to upgrade and add more users
* [ ] Direct standard tier users to contact sales

**Notes**

**Comment by dylanbhughes** [comment]
* Free & Starter -> "Upgrade to Standard"
* Standard & Enterprise -> "Contact Sales"
