### ISSUE TITLE
BUG: Can't delete custom role

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/ui#1217]
**Bug Description**

I have a custom role I created that is not assigned to anyone but I can't delete it because it is in use.

**Steps To Reproduce**
This is not enough to reproduce it
1. Create custom role
2. Try to delete it

Try:
1. Creating a custom role
2. Assigning it to someone
3. Switching them back to something else
4. Deleting the role - you shouldn't be able to

If that still doesn't work, in exact steps I did:
1. Create a new role
2. Assign it to myself (I lost privileges)
3. Asked a teammate to switch me back to Admin
4. Try to delete new role

**Browsers Tested:**
* [x] Chrome

----------
**Notes**

**Comment by znicholasbrown** [comment]
@kvnkho is there an error returned/displayed or is the button just disabled? (or maybe something else)

**Comment by kvnkho** [comment]
The role was lingering on a Service Account even if it was not attached to a user. Closing this issue.
