### ISSUE TITLE
BUG: Some CRON expressions don't seem to work when setting a CRON schedule via UI

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/ui#1221]
**Bug Description**
User reported that setting a CRON expression: `15 */1 * * *` did not work, but `15 * * * *` did. 

I haven't reproduced but here is the user description:

"BUG report:
schedules -> New schedule -> SCHEDULE (advanced=off) {Run every 1 hour … on the 15th minute of the hour.} + CREATE => Schedule with cron 15 */1 * * *
Flowrun with this schedule not start.
With edited to 15 * * * * works fine."

From: https://prefect-community.slack.com/archives/C0192RWGJQH/p1643963076977729 

Please investigate and if this is not a bug, close the issue.

**Comment by zhen0** [comment]
I just checked a flow schedule with this cron string and 10 runs were scheduled for 15 minutes past the hour.  Closing this issue as I could not recreate.
