### ISSUE TITLE
BUG: Service Account API Keys Not Appearing When Switching Tenants

### ISSUE THREAD

**Issue by TylerWanner** [PrefectHQ/ui#1227]
**Bug Description**

**Steps To Reproduce**

1. Open Service Accounts
2. Switch tenants
No API Keys will appear

**Browsers Tested:**
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by zhen0** [comment]
@ThatGalNatalie - I can't replicate this but I wonder if it's a slow loading like we saw with concurrency. Can you see if you can replicate? And try the same fix. Thanks.
