### ISSUE TITLE
Prefect Cloud Automations Page

### ISSUE THREAD

**Issue by creachel** [PrefectHQ/ui#1263]
## Current behavior

The dashboard automations has a good step by step UI but I have noticed that once an automation is created, the Automations list has some incorrectly generated summaries.

Example:
`When agents with {agent_name} are unhealthyKubernetesAgent, then {action}`

whereas it should be:
`When agents KubernetesAgent with {agent_name} are unhealthy, then {action}`

Additionally, the ordering of the automations (sorted by Date Created? From what I can see) makes it difficult to find which events have actions already. This can lead to duplication in automations.

## Proposed behavior

a) Ensure the automation summary is correctly displayed at all times
b) Give the user options to sort automations (or have a more logical way of sorting automations)
c) If possible, catch users from creating duplication automations

## Example

This would improve UX by a lot! :)

**Comment by zhen0** [comment]
Thanks @creachel - added to our backlog

**Comment by zhen0** [comment]
Hi @creachel - could you share a screenshot or more info of the first issue you're seeing?  I tried to replicate and can't. Thanks!

**Comment by creachel** [comment]
![image](https://user-images.githubusercontent.com/50759725/162324853-462992f4-8c82-44c9-a44c-aad821ddfef7.png)

Rendering looks fine when you first load the page but if you add a flow, there's a chance the tiles will render weirdly

**Comment by zhen0** [comment]
@creachel - the tiles look like the ones in that screenshot?  With the swirly text?  Or is that a privacy thing to hide details from your screen shot?  I've not seen anything like that before and still can't replicate.  Can you give any more info about how you are creating your automation?

Thanks for your comments about sorting automations.  I don't think that's something we'll be adding to V1 but good feedback for 2.0.

**Comment by creachel** [comment]
Hey @zhen0, sorry it took me so long to get back to you - I missed the notification. The swirly text was just a privacy thing of me blurring out flow names haha. I had another look at Automations and the issue seems to be resolved now. Thanks anyways!
