### ISSUE TITLE
BUG: Secrets - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by fong-kinduct** [PrefectHQ/ui#1269]
**Bug Description**
We store our AWS credentials in the built in prefect secrets store within prefect cloud. Occasionally (multiple times a week) we are alerted to failed flow runs where the secrets are not found, or unavailable.

**Steps To Reproduce**

1. Create a flow utilizing prefect cloud secrets.
2. Schedule the flow that uses prefect cloud secrets.
3. Wait for the failures.

----------
**Notes**

`[20 Apr 2022 8:54am]: Error during execution of task: ClientError([{'path': ['secret_value'], 'message': 'An unknown error occurred.', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}])`

Also Mentioned here: https://github.com/PrefectHQ/ui/issues/1236

**Comment by KelvinSan** [comment]
Any update on this ?

**Comment by madkinsz** [comment]
Hi! This issue is being tracked in https://github.com/PrefectHQ/prefect/issues/6056 and you can see updates there.
