### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by LadyMoth** [PrefectHQ/ui#1276]
**Bug Description**

1. 

**Browsers Tested:**
* [yes ] Chrome
* [ ] Firefox
* [ yes] Safari
* [ ] [Edge]
![Uploading Screenshot 2022-05-04 at 16.44.47.png…]()
)
* [ ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
Hi @LadyMoth - please provide a description when opening issues; you can always search for an answer on our [Discourse](https://discourse.prefect.io/) or ask a question in [Slack](https://join.slack.com/t/prefect-community/shared_invite/zt-14wbi5zjq-t3Es1tp0TMVsfksRzDNjog).
