### ISSUE TITLE
BUG: No Update in logs

### ISSUE THREAD

**Issue by hemantmehra14** [PrefectHQ/ui#1311]
**Bug Description**
Sometimes flow run in prefect for a long time with no update in logs. 

Only one info log appears in the UI.
```Submitted for execution: PID: XXXX```

Flow remains in progress for a long time. It happens rarely but when it happens there is no way to find out whether the flow was successful or not.

**Steps To Reproduce**

None

**Browsers Tested:**
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by zhen0** [comment]
Thanks for the report @hemantmehra14 - we'll keep an eye out for this but it's hard to make any fixes without more detailed and timely information.  I encourage you to report any further instances in the prefect slack community.  Thanks.

**Comment by discdiver** [comment]
Closing as stale.
