### ISSUE TITLE
BUG: UI strips new-line characters for Secret block

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/ui#1340]
**Bug Description**

Pasting a value with new line characters into the `Value` field of the `Secret` strips the new line characters.

**Steps To Reproduce**

1. Create a new Secret block in the UI with `Block Name` as `from-ui` and `Value` as,

```
line one
line two
```

2. Create a new Secret block with Python as,

```py
from prefect.blocks.system import Secret

data = """
line one
line two
"""

s = Secret(value=data)
s.save("from-code")
```

3. Compare the results,

```py
>>> from prefect.blocks.system import Secret
>>> Secret.load("from-code").get()
'\nline one\nline two\n'
>>> Secret.load("from-ui").get()
' line one line two'
```

**Prefect Version**

```
Version:             2.4.2
API version:         0.8.0
Python version:      3.9.13
Git commit:          65807e84
Built:               Fri, Sep 23, 2022 10:43 AM
OS/Arch:             darwin/arm64
Profile:             emil-default
Server type:         cloud
```

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by madkinsz** [comment]
UI issues for Prefect 2 should be reported in the PrefectHQ/prefect repository. https://github.com/PrefectHQ/prefect/issues/new?assignees=&labels=status%3Atriage%2Cui%2Cbug&template=2_ui_bug_report.yaml

**Comment by EmilRex** [comment]
Replaced by PrefectHQ/prefect#6949
