### ISSUE TITLE
Create Deployments from the UI

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/ui#1345]
User should be able to create deployments from the UI - we can use the wizard or a form to allow users to 
- Add name, description, and entrypoint
- Compose in storage and infra blocks (optional)
- Add schedules, work queues (optional)

Additional inputs: https://docs.prefect.io/concepts/deployments/

**Comment by williamjamir** [comment]
Create addition I want to see this feature as well :)

But I think the UI development is happening on this repository, perhaps would be better to create this issue there for better visibility.

https://github.com/PrefectHQ/prefect

**Comment by zhen0** [comment]
Hey @WillRaphaelson - I'm going to close this one as it refers to Prefect 2 and I believe we have an issue tracking that already.
