### ISSUE TITLE
Overenthusiastic scrollbars in both cloud and server UI

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/ui#175]
**Bug Description**

The most recent version of the UI is displaying extra scrollbars for everything that uses Vue list item groups. 
- This occurs when the UI is rendered in Chrome, Firefox, or Edge.
- This appears to affect Windows only.
- Tested on both cloud and server (from latest core release).

Adding the following CSS rule to override the default styling (`overflow:scroll`) fixes it for me:

```css
.v-list-item__content {
 overflow:auto
}
```

**Steps To Reproduce**

Using Firefox or Edge on a Windows machine or VM, visit the overview page for a specific flow (this issue appears to affect most pages of the UI, but is easily obvious on this page).

**Browsers Tested:**
* [X] Chrome (latest)
* [X] Firefox (80.0)
* [ ] Safari
* [X] Edge (85.0.564.41)
* [ ] IE

----------
**Notes**

![image](https://user-images.githubusercontent.com/5920864/91746631-69ca7680-ebac-11ea-9b2e-bd573baf8a49.png)

**Comment by znicholasbrown** [comment]
Thanks for reporting this @jnoynaert - I'm taking a look at this issue today once I can get a Windows machine set up.
