### ISSUE TITLE
Bug with checkpointing and mapped tasks

### ISSUE THREAD

**Issue by emcake** [PrefectHQ/ui#182]
## Description

Currently restarting a failed flow that has failed on some mapped tasks seems wrong in the following ways:

1. Previously successful mapped childs will re-run
2. `run_count` doesn't seem to change between restarts

## Expected Behavior

1. A previously successful mapped task should not be rerun by checkpointing if it has already succeeded
2. the `run_count` should up between runs.

## Reproduction

Here is a minimal flow that can reproduce this is below. Start a cloud run, it will fail on the first mapped task, but the other two will succeed. Use the 'restart' button in the top right of the UI to restart this flow-run. Note that previously successful mapped runs run again. Note that the first instance fails again, and (in the logs) `run_count` is still `1`, even though the UI clearly shows multiple runs.

```python

import prefect

@prefect.task
def task(x):
    prefect.context.get('logger').info(f'x = {x} and run_count = {prefect.context.get("task_run_count")}')
    if x == 0 and prefect.context.get('task_run_count') == 1:
        raise prefect.engine.signals.FAIL('fail on first attempt')
    else:
        return x + 1

@prefect.task
def summy(xs):
    return sum(xs)

with prefect.Flow('test-restarts') as flow:
    list = prefect.tasks.core.constants.Constant([0,1,2])

    mapped = task.map(list)

    summy(mapped)

flow.register(project_name='mattk')
```

## Environment

```
root@docker-desktop:/workspaces/prefect# prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.19.104-microsoft-standard-x86_64-with-debian-10.5",
    "prefect_version": "0.13.2",
    "python_version": "3.7.9"
  }
}
```

**Comment by cicdw** [comment]
Hi @emcake - I was able to reproduce and find the issue; this is a UI bug with the logic behind the "Restart from Failed" button (hence the transfer of the issue to the UI repo).  Working on a fix now!
