### ISSUE TITLE
Support for HTTPS/TLS

### ISSUE THREAD

**Issue by gabrielcalderon** [PrefectHQ/ui#210]
**Why**
Currently the UI is only server through HTTP.

**What**
Add support for passing TLS certs to the NGINX in front of PrefectHQ/UI Docker container.

**Notes**
There's a way to make TLS certs optional through NGINX config. The main problem would be that everything else is using "http" as the UI url.

**Comment by znicholasbrown** [comment]
Hi @gabrielcalderon - I believe #241 should resolve this with in-app references. You'll need to set up your own webserver (nginx or otherwise) with TLS support to sit in front of the UI container. I'm closing this issue but feel free to re-open if you feel this isn't resolved.

**Comment by gabrielcalderon** [comment]
Thanks for the update! I will look into using Nginx :-)
