### ISSUE TITLE
Make it more obvious that a user needs to start an agent

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/ui#215]
Currently, if a user has no agents, they see:
![image](https://user-images.githubusercontent.com/153965/92762190-5794c900-f360-11ea-9ff6-0f31138f9f48.png)

Since this is the common starting point for new users, there's an opportunity to make this more informative and helpful. For example, telling a user that they must start an agent to do work (a common misunderstanding for users that don't read the docs), or jumping-off to actions like creating a new agent config (thanks to the new persistence work by @joshmeek and @cicdw). As is, new users may not realize that this is actually a blocking problem for getting work done (if only due to its yellow color)

In addition, if there is late work AND no agents, that could be surfaced more obviously/visibily than if there's no work and no agents.

**Comment by cicdw** [comment]
Yea, good idea - an easy first fix can change the color + update the message when there are no agents.

**Comment by znicholasbrown** [comment]
@zhen0's PR (#214) will introduce some features to make this more obvious on the upcoming runs and flow page details tiles. Also agreed with @cicdw that we can change the tile color/message to make this more obvious and provide some links to the docs.
