### ISSUE TITLE
Duplicate Agent showing in Dashboard for each run

### ISSUE THREAD

**Issue by faultylee** [PrefectHQ/ui#244]
Thanks you guys for this great product :tada: 

## Description
For each execution of  `prefect agent start docker` we get one new agent showing in the dashboard. The name, label and token used is the same. Restarting multiple time, how the dashboard is filled with "dead" agents
![image](https://user-images.githubusercontent.com/1635211/93841479-4a63cc80-fcc6-11ea-84f0-b7993f27051d.png)

## Expected Behavior
For each unique execution of prefect agent there should only be 1 agent showing in the dashboard

## Reproduction
```
prefect agent start docker  --label production --name abc
```
Execute above with the same token, exit and execute again, each time a new agent appears 

## Environment
Prefect installed using `pip3` running on AL2 in EC2.

 `prefect diagnostics` -->
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.14.193-149.317.amzn2.x86_64-x86_64-with-glibc2.2.5",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.7",
    "python_version": "3.7.9"
  }
}
```

**Comment by faultylee** [comment]
Hi @joshmeek, thanks for the prompt response. It make sense. I wasn't sure what's what, lol. Not sure if it's already documented, maybe a "Known Issues" section on the release notes might be helpful, so we know what to expect, and probably also help improve the overall UX for new users.

Looking forward to the new agent update :+1:

**Comment by joshmeek** [comment]
Thanks for the feedback. I recall talking to @cicdw about how to better publicize platform issues/updates/etc. and a section like that would work well in there!

**Comment by cicdw** [comment]
Hi @faultylee - I have good news!

1. The agent tile issue has been fixed and released, so you should see more intuitive behavior from your Agent dashboard now.  In particular, Agents that register with the same type / name / labels and core version will be considered the same.
1. We now have a public changelog that we will be updating every 2 weeks or so!  Here's a link: https://www.prefect.io/public-changelog. We will be pushing out Cloud notifications (visible on your Dashboard) each time we publish a new entry.
