### ISSUE TITLE
"Agent problem" in server UI with agent running

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/ui#272]
The server UI is showing all upcoming runs with the red "Agent Problem" indicator that looks like it was introduced in  #217 , even though an agent is online. Is this just due to the agent tracking functionality not being included in the open version?

- This is using a local agent with local storage.
- Clicking "run now" on any of the runs executes the flow successfully as normal.
- The agent logs don't show any connection errors.
- The server logs show the successful check-in responses to the agent.
- I've tried various combinations of resets and refreshes (including clearing the docker build cache and re-deploying server, clearing browser cache etc)

This is using the Prefect core/server 0.13.9.

If this is due to a functionality mismatch, ideally UI users would just not see a warning, rather than an unresolvable one.

![image](https://user-images.githubusercontent.com/5920864/94643367-26ac1200-02d6-11eb-9df6-a3118ba3cb13.png)

**Comment by znicholasbrown** [comment]
Hi @jnoynaert - we've implemented a patch for this in #264 and should have the latest Core release retagged with that change later today; thanks for flagging! I'll leave this issue open until the UI image is retagged, at which point you'll need to re-pull that image.

**Comment by zhen0** [comment]
Hi @jnoynaert - the image is now retagged updated in Server so you should be able to re-pull.  Thanks again for flagging.
