### ISSUE TITLE
BUG: Server Cloud toggle can be hard to find

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/ui#284]
**Bug Description**

@jcrist mentioned that he recently visited cloud.prefect.io and was confused to see a Server backend rather than Cloud.  It also took a while to find the toggle to get back into Cloud. 

Jim's experience was perhaps rare - my guess is that server got set as his backend in localstorage a while ago and so he was taken to the Server UI and new users would get taken to Cloud and would only get to the server UI by finding the toggle.  **However, it highlighted that the toggle button between Server and Cloud is pretty hard to find and it seems like if we're going to have that button, we should make it easier to find.** 
We might also want to consider storing backend in session storage rather than local storage?

**Steps To Reproduce**

1. Go the cloud.prefect.io and toggle to Server in the sideNav. Close the page and go away for a while. 
2.  Forget that you've done that and come back to cloud.prefect.io. You will be taken to server rather than cloud. 

If you've visited before, you should remember where the toggle is but it's still pretty hard to find. 

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

If we don't want to make the button more obvious for everyone, we could consider adding a "Back to Cloud" button in a more visible place (like the top nav bar) if a user is at cloud.prefect.io and in the server ui, especially if there's no API connection.

**Comment by znicholasbrown** [comment]
I think so, yes, the next issue we want to solve is #614
