### ISSUE TITLE
BUG: Incorrect pluralization for concurrency slots

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#293]
**Bug Description**

When there is 1 concurrency slot in use, the concurrency notification reads `1 slots used`

----------
**Notes**

<img width="548" alt="Screen Shot 2020-10-05 at 7 08 13 PM" src="https://user-images.githubusercontent.com/27291717/95141104-4ad87a80-073e-11eb-80be-693b4a61a012.png">

**Comment by whimsicallyson** [comment]
@znicholasbrown this seems like something I could take on this week, yeah?

**Comment by znicholasbrown** [comment]
Definitely! All yours @whimsicallyson 😄
