### ISSUE TITLE
BUG: Error on flow group labels reset

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#320]
**Bug Description**

When resetting the labels on a flow group, a type error is thrown:
```
TypeError: Cannot read property 'labels' of undefined
```

**Steps To Reproduce**

1. Change the labels on a flow
2. Reset the labels

**Browsers Tested:**
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

![Screen Shot 2020-10-12 at 3 00 55 PM](https://user-images.githubusercontent.com/27291717/95781492-e9635f00-0c9b-11eb-8a67-605a6807800f.png)

**Comment by zhen0** [comment]
I believe this was fixed by #309 - I can only re-create in cloud.prefect.io or if I revert back to before that PR using local.

**Comment by znicholasbrown** [comment]
Confirmed this fix went out with https://github.com/PrefectHQ/ui/releases/tag/2020-10-13
