### ISSUE TITLE
BUG: Flows and Agents tiles are not reloading when the backend changes

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#36]
**Bug Description**

Since the flows and agents tiles/tabs are outside the landing loading, the components aren't receiving the apollo client refreshes they should be; this means the component's queries are being stopped but never restarted to fetch new data.

**Steps To Reproduce**

1. Navigate to the Dashboard > Flow tab
2. Switch backends

**Browsers Tested:**
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by zhen0** [comment]
Was closed by #123
