### ISSUE TITLE
Improve the tutorials 

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#361]
**Why**

The tutorials in the UI aren't well-maintained. 

Some issues with tutorials we should address:
- Readability; the current tutorials only contain a few steps and are using a stepper component to walk users through the instructions. This isn't particularly readable as it makes reading ahead or looking back difficult. We should instead move to a long-form version of the tutorials with something like a table of contents/sidebar for a breakdown of content/steps
- Maintainability; modifying the current tutorials requires understanding Vue components fairly well and having a good understanding of JS scoping. This discourages outside contribution and means any PRs to modify the tutorials end up being sizable (not straightforward to write or review); we should look at incorporating something simpler, ~~perhaps using a CMS to populate the tutorials or~~ using `.md` files as the basis of the tutorials that we could apply formatting and styling to in the UI

**What**

The tutorials:
* [ ] are easy to navigate and read through without extraneous user interaction (i.e. i shouldn't have to click to see a particular step)
* [ ] are styled to match the rest of the application
* [ ] are easy to modify for external contributors who may not have strong JS backgrounds
* [ ] filterable (for example Cloud/Server-specific tutorials)
* [ ] allow adding / removing existing tutorials without a large review/HTML-writing burden

**Notes**

Related to #281

**Comment by ThatGalNatalie** [comment]
For the readability, when you mention that we should move on to a long-form version, would it be similar to something like the [Gatsby](https://www.gatsbyjs.com/tutorial/), [React](https://reactjs.org/tutorial/tutorial.html), or [Nuxt](https://nuxtjs.org/guide) tutorials?  

I like the idea of a CMS but wouldn't it make it harder for someone to contribute? For example, if they saw a typo and wanted to correct it, they wouldn't have access to the CMS and would instead have to open an issue? 

@znicholasbrown

**Comment by znicholasbrown** [comment]
Those are great examples @ThatGalNatalie so yes - good point on the CMS, so I'll scratch that off since it goes against the spirit of the ticket.

**Comment by ThatGalNatalie** [comment]
So I would assume we would use VuePress for this? @znicholasbrown

**Comment by znicholasbrown** [comment]
Discussed offline but recording here for posterity: we probably don't need to introduce something as heavy as Vuepress to handle markdown since we can write our own markdown parser fairly easily. Whatever we write/implement should also be flexible as we look at user-generated md content from Core.
