### ISSUE TITLE
BUG: Scroll bars CSS issue

### ISSUE THREAD

**Issue by kfirstri** [PrefectHQ/ui#366]
**Bug Description**
There are empty scroll bars on all "card" elements in the UI

Dashboard - 
![image](https://user-images.githubusercontent.com/3606980/96846818-101f5380-145b-11eb-9653-acb94072f920.png)

Task View -
![image (6)](https://user-images.githubusercontent.com/3606980/96846827-131a4400-145b-11eb-94a5-e08b5630360c.png)

Flow View -
![image (5)](https://user-images.githubusercontent.com/3606980/96846830-131a4400-145b-11eb-870d-015dfa0d5f4f.png)

Agent Card -
![image (4)](https://user-images.githubusercontent.com/3606980/96846832-13b2da80-145b-11eb-931d-f5bfd3257a2e.png)

Disabling the CSS property
![image (7)](https://user-images.githubusercontent.com/3606980/96846825-11e91700-145b-11eb-9aed-7e3a105e8d96.png)

if I disable this css prop - 
```css
.overflow-y-scroll {
    overflow-y: scroll;
}
```
Then the scroll lines disappear but then the content overflows it's container

**Steps To Reproduce**
1. Install prefect with pip `pip install prefect` (latest version
2. run the server
3. go to localhost:8080

**Browsers Tested:**
* [X] Chrome - Version 86.0.4240.80 (Official Build) (x86_64)
* [X] Firefox
* [X] Safari
* [ ] Edge
* [ ] IE

**Comment by whimsicallyson** [comment]
hi @kfirstri! I'm taking a look at this bug, and I'm able to reproduce it while my colleague isn't. We think the difference is in the MacOS we're running--out of curiosity, what OS are you on?

**Comment by kfirstri** [comment]
Hi @whimsicallyson :)
Giving you lots of specs just to make sure - 
Model Name:	        MacBook Pro
Model Identifier:	MacBookPro14,3
Processor Name:	Quad-Core Intel Core i7
System Version:	macOS 10.15.7 (19H2)
Kernel Version:	Darwin 19.6.0
