### ISSUE TITLE
BUG: Failed Auth Loop after long inactivity

### ISSUE THREAD

**Issue by raphael-riel** [PrefectHQ/ui#371]
**Bug Description**
Sometimes, after a certain inactivity time (Either no focus on tab, or Sleep on MacOs, or both) the UI is blank and nothing happens unless I force Refresh the UI.

**Steps To Reproduce**
1. Have the UI open on Either Flow Definition or a Flow Run page (this Event is on FlowRun).
2. Switch to another tab.
3. Wait for a undetermined amount of time (My best guess would be something related to OAuth Token/Refresh Validity?)
4. Go back on Prefect UI

It's Blank and nothing happens.

Hard-Refresh the page and voilà, it's back. **No need to login again.**

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**
On Prefect Cloud.
MacOS using Chrome Version 86.0.4240.75 (Official Build) (x86_64)
For this particular even, I went back after the night (~16h including Computer Sleep).

![UponReturn](https://user-images.githubusercontent.com/474697/97002941-b1b0ae80-1508-11eb-8142-351142651fba.gif)

**Comment by znicholasbrown** [comment]
Hi @raphael-riel - thanks for reporting this, this is something I'm looking into and hope to have fixed soon 👍

**Comment by awaterman5** [comment]
Any updates on this ticket?  This has been an outstanding for me too in Prefect for several months also on Chrome for Mac OS X.  As a result I have to constantly close my browser tab for Prefect and open a new one, just to check on the status of prior FlowRuns.

**Comment by znicholasbrown** [comment]
Resolved by #679 and #688.
