### ISSUE TITLE
BUG: JSONInput component overruns container width on some screen sizes

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#374]
**Bug Description**

From the Community Slack, related to #325 

**Steps To Reproduce**

1. Unsure

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

![image](https://user-images.githubusercontent.com/27291717/97026863-f435b380-1527-11eb-8bd4-d9357c4b4ac1.png)

**Comment by zhen0** [comment]
I believe this was fixed with the addition of text wrap into code mirror in #370
