### ISSUE TITLE
BUG: Server Deployment of UI still connects to http://localhost:4200 for GraphQL

### ISSUE THREAD

**Issue by sattsb** [PrefectHQ/ui#383]
**Bug Description**
When prefect core is deployed on a remote host dna-prefect.company.com and accessed via http://dna-prefect.company.com:8080, the UI still connects to http://localhost:4200 and not the resolved URL for the UI

**Steps To Reproduce**
1. Deploy prefect server on a remote host
2. Navigate to UI 
3. The UI connects to localhost graphql endpoint at port 4200
4. If there is no localhost prefect running it will show not connected

**Browsers Tested:**
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Edge
* [X ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
Hi @sattsb - thanks for opening an issue! When deploying Prefect Server on a remote machine, you'll need to configure it to point to your deployment of Apollo. Do that, you can either set the environment variable `PREFECT__SERVER__APOLLO_URL="http://your_apollo_address:4200/graphql"` OR set this same variable in the `~/.prefect/config.toml` configuration file on the machine you're hosting Prefect Server from. For reference, here's a sample of that config file:
```toml
# ~/.prefect/config.toml

[server]
  [server.ui]
  apollo_url="http://your_apollo_address:4200/graphql"
```

Have you checked out our [docs on single node deployment](https://docs.prefect.io/orchestration/server/deploy-local.html#ui-configuration)? They include a section on UI configuration that will help you point your UI at your Apollo deployment. I'm going to close this ticket for now but if you find an issue with the above, feel free to reopen.
