### ISSUE TITLE
BUG: If multiple agents have same type + labels, only one shows up on "Agents" page

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/ui#384]
**Bug Description**

I found today that if I have two running agents with the same type and labels, only one of them shows up in the Prefect Cloud UI.

![image](https://user-images.githubusercontent.com/7608904/97490234-8ece3200-192e-11eb-9e93-2bce4aabf1d1.png)

**Steps To Reproduce**

1. log in to Prefect Cloud UI
1. generate a RUNNER token and use it to create two `LocalAgent`s (in different shells):
    ```shell
    prefect agent start -t ${PREFECT_RUNNER_TOKEN}
    prefect agent start -t ${PREFECT_RUNNER_TOKEN}
    ```
1. Navigate to "Agents" page in Prefect Cloud UI

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

I'm not sure yet if this is a UI issue or a Prefect Core server issue or a Prefect Cloud backend issue. I first noticed this in the UI, so I'm starting here.

I can think of a few possible causes:

* maybe agents are uniquely identified by the combination of `{type, label, IP address}`, so Prefect server doesn't care that I have two agent processes running
    - or other flavors of this that can be described as "I don't understand what uniquely identifies one agent"
* maybe the fix for #244 was not quite correct and could result in treating something as a duplicate when it isn't one
* maybe both agents are actually known to Prefect Cloud, and a regression has caused #36 to resurface
    - I tried to use the Interactive API in the Prefect Cloud UI to check this, but the query automatically generated by that tool resulted in an error
    - ```graphql
       query {agent() {id, created }}
       ````
    - > {
          "message": "Syntax Error: Expected Name, found \")\".",
          "locations": [{
            "line": 3,
            "column": 9
          }]
        }
    - ```graphql
       query {agent {id, created }}
       ````
    - > {
          "graphQLErrors": [{
            "message": "Unknown argument \"limit\" on field \"agent\" of type \"Query\".",
            "extensions": {
              "code": "GRAPHQL_VALIDATION_FAILED"
            }
          }, {
            "message": "Unknown argument \"offset\" on field \"agent\" of type \"Query\".",
            "extensions": {
              "code": "GRAPHQL_VALIDATION_FAILED"
            }
          }],
          "networkError": null,
          "message": "GraphQL error: Unknown argument \"limit\" on field \"agent\" of type \"Query\".\nGraphQL error: Unknown argument \"offset\" on field \"agent\" of type \"Query\"."
        }

I did also notice this issue with `KubernetesAgent`, so I don't believe it's specific to `LocalAgent`. I chose `LocalAgent` here because that was a lighter-weight reproducible example.

Thanks for your time and consideration.

**Comment by znicholasbrown** [comment]
Hi @jameslamb - this is a deliberate decision not to tie agents to specific processes; if two agents have identical names, versions of prefect, labels, and tokens, we assume that they're the same (remember that Prefect Cloud doesn't talk to an agent, an agent identifies itself to Prefect Cloud). So, if you wanted to spin up 2 uniquely-identified agents with the same settings, an easy way to do that is to pass the `--name` flag, which will tell the API to differentiate them. I've [opened a PR to the docs](https://github.com/PrefectHQ/prefect/pull/3591) to clarify this and help alleviate any confusion 😃

**Comment by jameslamb** [comment]
Ok thanks!

I guess I understand why this is done (instead of, say, agents generating their own random IDs),  so that you can have  a concept of an agent that is not communicating  "coming back online"  (instead of it looking like one died and a new one came to life).

What is the equivalent to passing that CLI flag when I create  `KubernetesAgent`s?  I create those by applying a manifest to a k8s cluster, not using the `prefect` CLI. I expect that's a common approach that people use.

**Comment by znicholasbrown** [comment]
@jameslamb you can set the agent name in the k8s manifest using the agent name env var:
```
name: PREFECT__CLOUD__AGENT__NAME
value: <<your agent name>>
```

**Comment by jameslamb** [comment]
perfect, thank you!
