### ISSUE TITLE
BUG: Refreshing the browser in a flow page redirects to blank page

### ISSUE THREAD

**Issue by mazar** [PrefectHQ/ui#385]
**Bug Description**
When browser is refreshed on `/default/flow/UUID` page, you are redirected to `/` (root) with blank contents.
Also, if you copy/paste the full URL of a flow page to a new browser tab, it redirects you to a blank root page.

**Steps To Reproduce**
1. Install Prefect server 0.13.12
2. Create a project
3. Register a flow
4. Goto the UI page for that flow
5. Hit refresh

**Browsers Tested:**
* [X] Chrome
* [ ] Firefox
* [X] Safari (The UI does not even show the Dashboard correctly)
* [ ] Edge
* [ ] IE

**Comment by zhen0** [comment]
I believe this was fixed by #354 and should work in 0.13.13

**Comment by mazar** [comment]
Correct, just upgraded to 0.13.13 and issue is no longer there. Thanks
