### ISSUE TITLE
BUG: Secret value margin is different from secret name margin

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#412]
**Bug Description**

The secret value input box has different margins from the secret name input box.

**Steps To Reproduce**

1. Visit the secrets page and create a new secret

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

![Screen Shot 2020-11-10 at 1 23 12 PM](https://user-images.githubusercontent.com/27291717/98716076-f76ad500-2358-11eb-9573-82d27e52be5b.png)

**Comment by whimsicallyson** [comment]
I'm not reproing this, are you able to anymore?

**Comment by znicholasbrown** [comment]
Yeah this was fixed in #585, forgot to close the issue, mb.
