### ISSUE TITLE
BUG: Team -> About Page: License Terms are not updating

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/ui#426]
**Bug Description**

The license page doesn't refresh license terms.

**Steps To Reproduce**

1. Look at the team -> account page in the UI
2. Update one of the license terms (users, flows, etc)
3. Leave the UI / stay on the page
4. License terms remain unchanged until manually refreshing the page

**Browsers Tested:**
* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
This issue should be resolved by the transition to usage licenses.
