### ISSUE TITLE
Navigate to a child Flow run, from a parent Flow in Prefect Server

### ISSUE THREAD

**Issue by roey-navina** [PrefectHQ/ui#439]
## Current behavior
Currently, Flows started as tasks in another Flow using StartFlowRun, aren't easily found or navigated to from looking at the graph or schematic of the main Flow, in Prefect Server.

## Proposed behavior
By clicking on the Task's rectangle in the graph, there should be a link to the actual Flow run.

**Comment by znicholasbrown** [comment]
Marking this as blocked and putting it in the backlog until Cloud/Server begin tracking flow runs, at which point we'll pick it up.

**Comment by cicdw** [comment]
**cc:** @joshmeek as I believe all we need to do here is publish an artifact link with the `StartFlowRun` task

**Comment by joshmeek** [comment]
Yep @cicdw that is a planned addition that will probably be out in next week's core release 🙂
