### ISSUE TITLE
BUG: Summary and Failed flows cards show incorrect metrics if postgres tables was updated by alembic

### ISSUE THREAD

**Issue by alex-hsp** [PrefectHQ/ui#462]
**Bug Description**
After upgrading my installation from 0.13.14 to 0.13.16 i found that Summary card and Failed flows cards was showing incorrect metrics like 300 flow runs in past hour which is not true. I queried one of such flow runs which complete a week ago and found that its `updated` field has todays timestamp. So i suppose it is automatically updated whenever postgres object changes. O

Object also changes if i run alembic migration. This is not what user expect to see.

There was a suggestion to use `created` field instead of `updated` in UI graphql query that fetch these stats.

**Steps To Reproduce**

1. Create a flow run, possibly manually update it so its `updated` field is 60 days old
2. Verify it is not shown in Summary and Failed flows statistics for any of the time ranges
3. Create some alembic migration and run it
4. Flow run will be shown in UI regardless of time range set

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

**Comment by zhen0** [comment]
Closed by #1028
