### ISSUE TITLE
BUG: Can't click to Task Run from Search Bar

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/ui#466]
**Bug Description**

Whenever I search for a task run in the search bar, I'm not able to click through to the task run page.

![search-click](https://user-images.githubusercontent.com/13255838/100288205-09d53900-2f2b-11eb-9cb4-31e3b3ae2a1c.gif)

**Steps To Reproduce**

1. search for a task run by ID
2. attempt to click
3. nothing happens :( 

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
I can't reproduce this @cicdw, do you have any other info you can provide?

**Comment by cicdw** [comment]
Hm let me check the console logs

**Comment by cicdw** [comment]
The logs are totally empty other than 
```
[Violation] 'setTimeout' handler took <N>ms
```
which I think is unrelated... it's been happening for a few days for me, I'll try to see what else I can learn

**Comment by madkinsz** [comment]
I cannot reproduce on Firefox. Interestingly, you can't search for task runs by name? I had to use the API to grab an ID

**Comment by znicholasbrown** [comment]
Yeah you're correct @madkinsz, that's related to task run indexing performance, [ticket for that is here](https://github.com/PrefectHQ/cloud/issues/2784).

**Comment by zhen0** [comment]
Hmmm.. I can reproduce using dev.prefect.io, staging.prefect.io and cloud.prefect.io.  But frustratingly I can't reproduce using localhost in any environment, which makes it difficult to debug.

**Comment by znicholasbrown** [comment]
I've moved this to the backlog until we can faithfully reproduce.

**Comment by zhen0** [comment]
Checked on this and can still recreate.  Given that it's been in the backlog for so long, I'd be interested in views for prioritization @cicdw. 

https://user-images.githubusercontent.com/40272060/136837877-58e57460-51c7-4754-ac3f-73e026c877a2.mov
