### ISSUE TITLE
BUG: Extra width on selection bar under dashboard navbar

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/ui#47]
**Bug Description**

The selection bar (if that's what you call this) creeps over under Flows on the dashboard:

![image](https://user-images.githubusercontent.com/40716964/89243847-fc3e2100-d5d2-11ea-9f95-320e81ba3664.png)

**Steps To Reproduce**

```
prefect server start -v alpha
```

Visit `localhost:8080` 

Clicking on to the flows page resets the width:

![image](https://user-images.githubusercontent.com/40716964/89243953-47583400-d5d3-11ea-80f7-3be3ef76ad40.png)

![image](https://user-images.githubusercontent.com/40716964/89243957-4b845180-d5d3-11ea-91b4-f300944144e6.png)

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by zhen0** [comment]
I can re-create this but not reliably.  It 's possible it's something in the Vuetify v-tabs code as I can't see anything in our code that would cause this.  I'll keep an eye out for any another insight.

**Comment by znicholasbrown** [comment]
This was resolved by a Vuetify upgrade - can reopen if we see again.
