### ISSUE TITLE
BUG: Navigation to flow settings does not work after refresh

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/ui#486]
**Bug Description**

When I refreshed a Flow settings page, I was directed to the Overview page but the Settings button was still highlighted. I could not navigate to the Settings page again without clicking the Overview (or another) button first.

**Steps To Reproduce**

1. Navigate to https://cloud.prefect.io/prefect/flow/f5bf2b3f-89bd-43c7-b057-31eb94a35afc?settings=
2. You should be on the "Overview" page now
3. Attempt to navigate to settings and fail (nothing happens)

or

1. Navigate to any flow settings page and refresh the browser
2. Resume at 2 above

**Browsers Tested:**
* [ ] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

![Screen Shot 2020-12-02 at 4 22 14 PM](https://user-images.githubusercontent.com/2586601/100938596-d1dd7100-34a9-11eb-94f0-bc8a78583f5f.png)

**Comment by jcrist** [comment]
I've noticed this for any tab in the flow page as well ("Run", "Schematic", etc...). As Michael said, the tab logic seems to be on url change, so if the url already thinks you're in the tab clicking on the tab will do nothing.
