### ISSUE TITLE
HOW-TO: Notifications in Dashboard 

### ISSUE THREAD

**Issue by Eumenidies** [PrefectHQ/ui#504]
I am trying prefect as a replacement of airflow. And I 'm interesting at the page "Notifications" in Dashboard, but I don't know how to send notification to there. PLEASE let me know if it is a future feature or only in cloud ui?

**Comment by znicholasbrown** [comment]
Hi @Eumenidies - you can configure notifications to that page on any of your flows by selecting a flow and going to Settings > Cloud Hooks. From there you'll select `Prefect` and select the states on which you want to receive notifications ✅

**Comment by Eumenidies** [comment]
> Hi @Eumenidies - you can configure notifications to that page on any of your flows by selecting a flow and going to Settings > Cloud Hooks. From there you'll select `Prefect` and select the states on which you want to receive notifications

Thanks a lot!!! great help!!!
