### ISSUE TITLE
Add a "How did you hear about us" dropdown to the signup flow

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#505]
**Why**

We want to better understand where users are coming from. 

**What**

* [ ] a user is prompted to select how they heard about Prefect during the signup flow
* [ ] responses are anonymously catalogued

**Notes**

cc @dylanbhughes

**Comment by dylanbhughes** [comment]
Example options: 
<img width="762" alt="Screen Shot 2020-12-14 at 10 58 40 AM" src="https://user-images.githubusercontent.com/2325367/102103810-71302b80-3dfb-11eb-96e0-270f554f931d.png">

**Comment by whimsicallyson** [comment]
@dylanbhughes when you're back, let's discuss where this data is going and how its getting there!

**Comment by dylanbhughes** [comment]
@whimsicallyson and I synced this morning 👍

**Comment by znicholasbrown** [comment]
Resolved by #615
