### ISSUE TITLE
BUG: Chrome tab frozen and cpu-intensive

### ISSUE THREAD

**Issue by raphael-riel** [PrefectHQ/ui#513]
**Bug Description**
This is a bug that I have since the my first time with Prefect Cloud UI.
I wasn't able to properly collect data to help pinpoint what's going on, so I was always postponing the report.

Today I managed to collect what I can describe as "the most info I have".

I am keeping a Prefect (only one) tab always open since it's one of my "daily" tools.
On regular basis, when returning back to the tab (it was not focused) the screen is blank and frozen.
Can't right-click, can't open DevTools, and closing it will prompt the Chrome's popup telling the process is irresponsive.
I managed to have the Devtool open once and tried to take a RAM snapshot, with no success, the whole tab-process is hanging.
The only way to have access back to Prefect's UI is to close the tab and reopen it (Reloading won't work... it's staying frozen).

## Upon returning:
![image](https://user-images.githubusercontent.com/474697/102619777-f886e300-410a-11eb-8b5a-1d168ce8c7d4.png)

## Chrome's Task Manager
Prefect's tab is the only one not reporting it's RAM.
![image](https://user-images.githubusercontent.com/474697/102620276-c45ff200-410b-11eb-8b3a-6f3d82bacabd.png)

## Activity Monitor show ~1Go RAM and 100% (one thread) for this process
![2020-12-18 at 8 17 AM](https://user-images.githubusercontent.com/474697/102619904-2c620880-410b-11eb-9919-b4132e8501ac.png)

**Steps To Reproduce**
1. Do some work on Prefect
2. Keep the tab open and go elsewhere
3. Go back after some time.

Sorry, I have nothing more than this.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

A) Can this be related to #371, in which the Login process was endlessly looping? My hypothesis is that something is accumulating and consuming all ressources.

B) *Sometimes* the tab unfreeze by itself after some wait time; which makes me think this could really be related to what's described in "A".

**Comment by znicholasbrown** [comment]
@raphael-riel this should be improved a lot by #679 and #688 - I'll close this but feel free to re-open if you're still seeing issues.
