### ISSUE TITLE
BUG: ClientFailed states are shown as null 

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#514]
**Bug Description**

Related to: https://github.com/PrefectHQ/prefect/issues/3874

Mapped children displays show `ClientFailed` states as `null`

----------
**Notes**

See the screenshots in the related ticket in Core

**Comment by cicdw** [comment]
@znicholasbrown FYI this might be trickier than your description suggests; the actual state in the DB for these runs is in fact `null` so the UI is showing accurate information.  `ClientFailed` states only exist client-side whenever a state fails to get set for some reason.

I haven't been able to tell how this can happen, as every time a task run is created it is created with a `Pending` state.

**Comment by znicholasbrown** [comment]
That explains why I've been unable to find any task runs in that state 😄
