### ISSUE TITLE
IAPI: Re-add URL-encoded queries

### ISSUE THREAD

**Issue by whimsicallyson** [PrefectHQ/ui#519]
**Why**
Our home-grown IAPI had the ability to share URL-encoded queries, and automatically populate a query from a URL. GraphiQL doesn't have this by default, but it would be nice (they may have it as an option that I didn't activate)

**What**
Find a way to implement URL-encoded queries with our new API explorer

**Comment by whimsicallyson** [comment]
ref: https://github.com/graphql/graphiql/issues/1003

**Comment by znicholasbrown** [comment]
Closed by: #529
