### ISSUE TITLE
api page gives a blank page when switching between routes 

### ISSUE THREAD

**Issue by ThatGalNatalie** [PrefectHQ/ui#525]
**Bug Description**
When visiting the api page for the first time, it will display the page but if you switch to a different route and head back to the api page, it gives a blank page. 

**Steps To Reproduce**
1. When arriving at the Dashboard, head to the api page
2. Click back to the dashboard or any other route
3. Head back to the api page 

**Browsers Tested:**
* [x] Chrome
* [x] Firefox
* [x] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

https://user-images.githubusercontent.com/40726391/103254530-85674300-493a-11eb-9500-8ff9be448856.mov

**Comment by ThatGalNatalie** [comment]
Actually not sure if this a bug or just my settings but it displays on the first visit 

@whimsicallyson

**Comment by whimsicallyson** [comment]
hm, I'm seeing this on dev.prefect as well, but there are no errors showing up in the console. not sure why this could be occurring?
