### ISSUE TITLE
Search by State in tables

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/ui#540]
**Why**

Often times I'm very interested in a particular task run by its state in the tables in the UI. It would be great to be able to search by fields other than the name, including state and even timestamp.

**What**

* [ ] User comes to the Flow Run page for a running flow
* [ ] As the flow is running, the user sees that some task runs are in a failed state
* [ ] User wants to see only failed task runs in a failed state for a certain mapped task
* [ ] User searches by "Failed" and the task name
* [ ] List filters

**Notes**

**Comment by madkinsz** [comment]
Hmm I'm curious how this would be implemented efficiently -- especially for a big table like task runs.
