### ISSUE TITLE
BUG: Relative link artifacts not rendered as links

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/ui#549]
`StartFlowRun` tasks post a link artifact using a relative URL, these artifacts aren't rendered as links (unclickable) in the UI, which prevents using them to navigate to the linked flow run.

<img width="837" alt="Screen Shot 2021-01-12 at 10 19 26 AM" src="https://user-images.githubusercontent.com/2783717/104341969-f91f5900-54bf-11eb-8d39-9f60d16a5376.png">

**Comment by bnaul** [comment]
Any idea if there's a quick fix for this (@znicholasbrown ?)? We have flows-from-flows that go several layers deep so navigating through them is kind of a pain currently.

**Comment by znicholasbrown** [comment]
Hi @bnaul - I've opened PR #559 that'll convert these links to navigable ones in the UI; I imagine this to be a stop gap until we come up with a better interface for artifact links (particularly those generated from `StartFlowRun` tasks). Let me know if this is helpful!

**Comment by sm-Fifteen** [comment]
The solution from #559 causes another problem to arise for non-http URIs. For instance, a lot of the tasks I'm running are creating files on servers that are meant to be accessed via FTP, SMB or SFTP, and I'm saving artifact URLs with schemes that are meant to reflect that. Using the current regex-based check, these are all interpreted as relative URLs, with results looking like `http://prefect-server/default/flow-run/ftp://ftp-server/my-file.csv`.

This only affects the href, not the URL being shown, but is still annoying.
