### ISSUE TITLE
Recent task failures pane blinks periodically

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/ui#552]
Not sure if this is a bug or not, but I find the blinking of the recent task failures pane distracting. The motion on the screen draws the eyes to it as if it's changing with new information, but it's not, it's just blinking. See attached gif.

![Screen Recording 2021-01-13 at 4 37 13 PM](https://user-images.githubusercontent.com/2783717/104518910-24886d80-55be-11eb-9095-6b2c4162712e.gif)

**Comment by madkinsz** [comment]
This takes about 10 seconds, just so nobody else goes crazy staring at it.
