### ISSUE TITLE
BUG: Clean Up Agents Button

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/ui#571]
**Bug Description**

I just hit the clear agents button for our team, and only some of the unhealthy agents were cleared.

**Steps To Reproduce**

1. Went to Agents tab
2. Pressed "Clean Up" button
3. Only some agents cleared
4. Pressed button again
5. Agents remained

**Browsers Tested:**
* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

https://app.logrocket.com/qetfiw/cloud-web-ui/s/4-2368e0da-c3e5-46da-b59f-e16dbcc65015/0?filters=%255B%257B%2522id%2522%253A%2522HJOs2-6yd%2522%252C%2522type%2522%253A%2522userID%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522auth0%257C5d267468a614960c643dab0e%2522%255D%257D%255D&fromTab=latest
<img width="1440" alt="Screen Shot 2021-01-25 at 10 30 36 PM" src="https://user-images.githubusercontent.com/2325367/105796632-40482800-5f5d-11eb-8863-b97f5f3d2005.png">

**Comment by aroder** [comment]
I see the same behavior. Chrome on windows. Doesn't seem to cause an error nor does it initiate a network request

**Comment by zhen0** [comment]
I can't actually reproduce this issue but I can see it on your log rocket link.  I've added some better error handling in #591 so we can track this and should have more information to fix it if we see it again in the future.

**Comment by dylanbhughes** [comment]
@zhen0 I suspect it might only pertain to agents created before a certain date, if that's helpful
