### ISSUE TITLE
Password protect UI

### ISSUE THREAD

**Issue by mastoltejr** [PrefectHQ/ui#572]
I'd like to put password protection so not just anyone can edit our flow schedules.
Is this possible ?

**Comment by znicholasbrown** [comment]
Hi @mastoltejr - authentication isn't something we support at the moment in Prefect Server given that it's complicated and highly-dependent on infrastructure/org needs. Our opinionated and best-practice approach to auth can be seen in [cloud.prefect.io](https://cloud.prefect.io) - if you need authentication/authorization I'd recommend you use Cloud instead, which was designed for users working with sensitive data that needed these things by default.
