### ISSUE TITLE
BUG: Backend Switch Can't Be Accessed if not logged into Cloud

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/ui#581]
**Bug Description**

If a user is in Server and switches to Cloud they are taken to the login screen of Cloud.  There's then no simple way of getting back to Server without either clearing local storage or signing into/signing up for Cloud. 

**Steps To Reproduce**

1. Log out of Cloud or use an incognito window. 
2. Open Server using local host
3. Use the backend switcher to go to Cloud.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

Based on comments from the community slack: https://prefect-community.slack.com/archives/C0192RWGJQH/p1611922573044900

**Comment by znicholasbrown** [comment]
Closing in favor of #614
