### ISSUE TITLE
BUG: unresponsive when user has zero teams

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/ui#623]
**Bug Description**

Prefect UI is unresponsive when a user has no team selected and zero teams to choose from. A redirect to "create a new Team" is needed when no option is found.

**Steps To Reproduce**

1. Go to User icon (top right) >> Account Settings
2. In the Teams tab, remove all teams
3. Loading hangs. Refreshing page starts the bug.
4. Reload the https://cloud.prefect.io/ page
5. Everything should now be in a "bugged" state, where no links work beside the "help" hyperlinks. This includes the ability to sign-out.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

1. Clearing cache and signing back in does not fix.
2. Inspecting html yields fail queries that continue to loop (see image below)
![image](https://user-images.githubusercontent.com/47992949/108610804-936b9a00-73a6-11eb-8a3d-490aebecd330.png)

**Comment by znicholasbrown** [comment]
Hi @jacksund - this is something we're looking to solve soon but isn't doable yet at the API level due to the way tokens are scoped. In the meantime we'll add some more helpful screens so the UI doesn't break in scenarios like this.

**Comment by jacksund** [comment]
Thanks! My currently account is "broken" because of this bug, and I actually had to sign up with a separate email to continue working haha. Can you let me know when a temporary fix as been added?

**Comment by znicholasbrown** [comment]
Send me a message via [Slack](https://join.slack.com/t/prefect-community/shared_invite/zt-at5l6diu-m7EsnFdpjgGL68l0WMox~w) (I'm nicholas with a Prefect P next to my name) @jacksund and we can get your original account sorted ahead of that!

**Comment by zhen0** [comment]
Closing in favor of #978
