### ISSUE TITLE
BUG: Case task runs without `end_time`s do not terminate properly in the flow run timeline

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#626]
**Bug Description**

When a `case` task runs, it doesn't have and `end_time` populated in the database. In this case, the flow run timeline shows an indefinite task run duration and a skewed timeline:
![image](https://user-images.githubusercontent.com/27291717/108757361-bf5a5d00-7517-11eb-9d3d-c02541fcf38f.png)

**Steps To Reproduce**

1. Create a flow with a case statement

**Browsers Tested:**
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by gryBox** [comment]
@znicholasbrown I think the bug occurs only with `mapped` cases.

This flow works:

from random import random

from prefect import task, Flow, case
from prefect.tasks.control_flow import merge

@task
def check_condition():
    return random() < .5

@task
def action_if_true():
    return "I am true!"

@task
def action_if_false():
    return "I am false!"

@task
def another_action(val):
    print(val)


with Flow("conditional-branches") as flow:
    cond = check_condition()

    with case(cond, True):
        val1 = action_if_true()

    with case(cond, False):
        val2 = action_if_false()

    val = merge(val1, val2)

    another_action(val)


# Register 
flow.register(
    project_name="lmap", labels=["make-lmap"],
    build=True   
)

**Comment by gryBox** [comment]
@znicholasbrown  Here is a reproducible example with `ifelse`

```
from prefect import task, Flow, case, Parameter
from prefect.tasks.control_flow import merge, ifelse

@task
def check_condition(my_num):
    return my_num < .5

@task
def action_if_true():
    return "I am true!"

@task
def action_if_false():
    return "I am false!"

@task
def another_action(val):
    print(val)


with Flow("conditional-branches") as flow:
    num_lst = Parameter("num_lst", default=[1, 2])
    
    cond = check_condition.map(num_lst)

    val1 = action_if_true()
    val2 = action_if_false()

    ifelse(
        cond,
        val1,
        val2,
        mapped=True
    )

    val = merge(val1, val2)

    another_action(val)


# Register 
flow.register(
    project_name="lmap", labels=["make-lmap"],
    build=True   
)
```

![image](https://user-images.githubusercontent.com/16763201/108762890-44447700-7516-11eb-9cfd-d5fafcb07989.png)

**Comment by znicholasbrown** [comment]
Thank you @gryBox!
