### ISSUE TITLE
BUG: Agent "Clean up" button is missing

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/ui#635]
**Bug Description**

Previously there was a "Cleanup" button that deleted all stale agents from the agents tab -- this button is no longer present.

**Steps To Reproduce**

1. Visit the agents tab when there are stale / dead agents

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
Resolved by: https://github.com/PrefectHQ/ui/pull/617 (should go out in the next release)
