### ISSUE TITLE
BUG: Double clicking Quick Run kicks off two flow runs

### ISSUE THREAD

**Issue by AndrewHannigan** [PrefectHQ/ui#637]
**Bug Description**
 Double clicking Quick Run kicks off two runs
**Steps To Reproduce**

1. Double click Quick Run on a Flow
2. Go to Dashboard and see two scheduled flow runs

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------

This can happen quite easily and unintentionally when using a track pad.  Expected behavior would be for only the first click on a quick run button to trigger as flow run.  Subsequent clicks should be ignored.

**Comment by znicholasbrown** [comment]
I think we should disable this button immediately after click (or put it in a loading state) to resolve this; thanks for the report @AndrewHannigan !
