### ISSUE TITLE
Simplify navigation from flow run page to latest version of flow

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/ui#649]
Developing a flow against prefect cloud may require some iteration, with the following common workflow:

1. Register flow
2. Click "quick run" to kick off a flow run, navigating you to a flow run page
3. Watch the flow run progress until an error occurs
4. Edit the local code to fix the bug
5. Re-register the flow (bumping the flow version)
6. Kick off a new flow run with the new version

Unfortunately navigating from the failed flow run page to the flow page for the latest flow requires two UI actions:

- Click the flow name in the breadcrumbs in the upper left corner. This brings you to the flow page for the now outdated version.
- Navigate to the latest version of the flow in the "Version" dropdown in the upper right corner, and navigate to the latest version.

After a few iterations, this process becomes annoyingly slow. It would be nice to provide a single UI interaction to get from a flow run page to the latest version of the flow.

I'm not sure if changing the flow name link to navigate to the latest version makes the most sense, or if another UI element should be added. I personally never feel the need to look at old *flow* pages for previous versions of a flow, so navigating to that page seems less useful to me, but others may feel differently.

**Comment by znicholasbrown** [comment]
Closed by #759
