### ISSUE TITLE
BUG: Task Runs is empty

### ISSUE THREAD

**Issue by semcha** [PrefectHQ/ui#669]
**Bug Description**

Widget "Task Runs" empty after run.

**Steps To Reproduce**

1. This task: https://pastebin.com/eMFYJNtm
2. prefect version - 0.14.12, Chrome 89
3. Run task and and you will see empty "Task Runs" widget: https://prnt.sc/10mjjnf

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
Hi @semcha - thanks for opening this ticket; are you running this on Prefect Server or Prefect Cloud?

**Comment by semcha** [comment]
Hi @znicholasbrown! Prefect Server

**Comment by znicholasbrown** [comment]
Great - thanks for confirming that; when you're on that page do you have any errors in the JS console? You can access this in Chrome through the Menu in the top right > More tools > Developer console > Console tab.

**Comment by semcha** [comment]
@znicholasbrown Is this format comfortable? Or is it better to attach a log file
https://prnt.sc/10mkemu

**Comment by znicholasbrown** [comment]
Ah that's perfect - thank you @semcha; a fix for this was just released. The next version of Core (which will be released in the next day or so) will contain the UI image with this fix; otherwise you can pull the latest tagged image of the UI by passing the `--ui-version "2021-03-15"` flag to your `prefect server start` command :)

**Comment by semcha** [comment]
@znicholasbrown Unfortunately, it didn't help :(
https://prnt.sc/10mkqpb

**Comment by znicholasbrown** [comment]
Sorry @semcha - can you try with this tag? `2021-03-15a`? Looks like we missed a reference there

**Comment by semcha** [comment]
@znicholasbrown Now it works! Thank you so much. You make a great product :)
