### ISSUE TITLE
BUG: Task-view table cannot sort by Duration

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/ui#687]
**Bug Description**
the `/simmate/task/<task_id>/` view is unresponsive when the user tries to sort by the "Duration" column. The following graphql error is thrown:
```
{message: "Variable "$orderBy" got invalid value { duration: … by type task_run_order_by. Did you mean version?", extensions: {…}}
```

**Steps To Reproduce**

1. Navigate to any non-parameter Task view
2. Click on the "Duration" column header (which will not change the view)
3. Inspect html to view error

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by znicholasbrown** [comment]
Hi @jacksund - since `duration` isn't a field coming from the API, we can't enforce sorting on the UI. As such, we've disabled that sorting column since it was broken. We can re-open this if that changes API-side.
