### ISSUE TITLE
BUG: The "current" label in the teams section is illegible

### ISSUE THREAD

**Issue by ThatGalNatalie** [PrefectHQ/ui#717]
The "current" label is illegible in both dark and light mode 

**Steps To Reproduce**
1. Click on "Switch team"
3. There should be a "current" label under the currently selected team 

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**
<img width="449" alt="dark-mode" src="https://user-images.githubusercontent.com/40726391/113333898-e145bd00-92d7-11eb-8cdf-f0b592a013be.png">
<img width="423" alt="light-mode" src="https://user-images.githubusercontent.com/40726391/113333909-e440ad80-92d7-11eb-92b0-079687cbb933.png">

**Comment by ThatGalNatalie** [comment]
@whimsicallyson oh my bad. I Forgot to assign myself. I just made a [pr](https://github.com/PrefectHQ/ui/pull/737) for this

**Comment by whimsicallyson** [comment]
way to be on top of things! I'll take a look :)

**Comment by whimsicallyson** [comment]
this got merged in :)
