### ISSUE TITLE
Create a mixin to handle licensing and permissions

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#718]
**Why**

We currently check licenses and permissions in most of our components/pages but in different ways. Centralizing / standardizing this will reduce the maintenance burden of license/permission checks and prevent us from needing to add this functionality for every new feature.

**What**

* [ ] a license/permission mixin exists which allows us to easily check for the ability to perform certain actions/view certain screens

**Notes**

**Comment by znicholasbrown** [comment]
This may not require a mixin; we could extend the `license` store to do the same thing.

**Comment by ThatGalNatalie** [comment]
For this, I don't think we should use a global mixin. Most of the articles that I read indicate that a global mixin should be used with caution as it will affect every Vue instance created afterwards and it could also cause naming conflicts. In addition, it will also affect third party components and I don't think every single component will need to know about license/permissions so we're  not really using it for its intended use that way. Thoughts? 

So far, I have only found 6 of the same license/permission checks (`flowConcurrency`, `isSelfServe`, `isUsageBased`, `isCurrent`, `planType`, and `hasRBAC`)

**Comment by znicholasbrown** [comment]
That makes sense - is this an action on the license store then?

**Comment by ThatGalNatalie** [comment]
I was thinking more of getters

**Comment by zhen0** [comment]
Closed by #763
