### ISSUE TITLE
BUG: Can't create schedule if default parameters are not provided

### ISSUE THREAD

**Issue by mashun4ek** [PrefectHQ/ui#765]
**Bug Description**

**Steps To Reproduce**

1. Use following flow:
```
from prefect import task, Flow, Parameter
import prefect
@task(log_stdout=True)
def say_hello(name):
    print("Hello, {}!".format(name))
name = Parameter("name", required=False)
with Flow("Test not required parameters with schedule") as flow:
    say_hello(name)
flow.register(project_name="Training")
```
2. Create a schedule via UI without parameters.
3. Following notification will appear: 
`There was a problem creating your schedule, please try again shortly. Error message: Error: GraphQL error: Invalid clock provided for schedule: {'type': 'IntervalClock', 'interval': 60000000, 'parameter_defaults': {'name': None}, 'start_date': {'dt': '2021-04-12T12:50:37.712905', 'tz': 'America/New_York'}}`.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

Slack: https://prefect-community.slack.com/archives/C0192RWGJQH/p1617103607042800

**Comment by zhen0** [comment]
This should be addressed by https://github.com/PrefectHQ/ui/pull/773
