### ISSUE TITLE
Activity Filter in Server Mode UI is broken

### ISSUE THREAD

**Issue by realknorke** [PrefectHQ/ui#78]
## Description

Activity filter "by type" does not work.

<img width="367" alt="activity" src="https://user-images.githubusercontent.com/8793173/88367720-bbe9d200-cd8c-11ea-9ec6-4bccab107990.png">

## Expected Behavior

Set filter to SCHEDULED and only schedules shoult be shown…

## Environment

Prefect v0.12.5 in Server Mode with LocalEnvironment and small Dask cluster.

**Comment by znicholasbrown** [comment]
This has been resolved with the newest version of Server 👍
