### ISSUE TITLE
Add mutation example and more query examples to the InteractiveAPI

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/ui#830]
**Why**

Some users have communicated that it's difficult to get started using the GraphQL API, with the first point of contact usually being the InteractiveAPI. We can improve this experience by providing some better startup examples.

**What**

* [ ] a user can see better examples of queries and mutations that would return real data when they visit the InteractiveAPI page

**Notes**

cc @kmoonwright for potential queries

**Comment by kmoonwright** [comment]
Common queries and mutations for Cloud users include...
**Queries:**
Get Flow ID
```
query {
    flow (
        where: {
            name: {_eq: <FLOW_NAME>}
            project: {name: {_eq: <PROJECT_NAME>}}
        }
    ){
        id, name, project {name}
    }
}
```

Failed task runs of a flow run:
```
query {
    task_run(
        where: {
            state: {_eq: "Failed"},
            flow_run_id: {_eq: "<FLOW_ID>"},
        }
    ) {
        task {name}, created, end_time,
    }
}
```

Last 10 flow runs of a flow (by ID) and their final state
```
query {
    flow_run(
        where: {flow_id: {_eq:"<FLOW_ID>"}},
        order_by: {updated: desc},
        limit: 10
    ) {
        id, state, state_message, name, scheduled_start_time
    }
}
```

**Mutations:**
create_flow_run
delete_flow_run
set_flow_group_labels_input
