### ISSUE TITLE
BUG: Permission issues in dev

### ISSUE THREAD

**Issue by ThatGalNatalie** [PrefectHQ/ui#903]
**Description**
As we are in the process of completely switching to permission based gating, there my be times when things should be gated but they're not or vice versa. I've made this list to keep track of what needs to be fixed and what has been fixed. If you see a bug, feel free to add to it to this ongoing list. 

**Issues:**

- [x] Edit and delete buttons are still shown in the Members page if they are logged in as a USER
- [x] The "Clear Late" button in the Dashboard, Flow, and Agent page is not disabled if the user does not have run permissions
- [x] The run flow now is not gated on run permissions

**Comment by zhen0** [comment]
- [ ] Remove agents has no permission checks

**Comment by ThatGalNatalie** [comment]
Permissions audit 

- [ ] Cancel Button (Flow run) 
- [ ] Cancel Button (Task run) 
- [ ] Delete Flow Button 
- [ ] Label Edit 
- [ ] Resume Button (Task run)
- [ ] Resume Button (Flow run)
- [ ] Schedule Toggle 
- [ ] Set State button (Flow run)
- [ ] Set State button (Task run)
- [ ] Change Plan Dialog (team settings)
- [ ] Change Plans (plans page)
- [ ] Delete Agent buttons (Agent page)
- [ ] Create new project button (Dashboard)
- [ ] Clear late run button (Dashboard)
- [ ] Clear late run button (Flow)
- [ ] Add Automations Card (Automations)
- [ ] Run now button (Flow)
- [ ] Cloud Hooks (Flow )
- [ ] General - move flows between projects, version locking,  (Flow/Settings)
- [ ] Actions bar - start now, schedule (Flow)
- [ ] Actions bar - start now, restart, delete buttons (Flow run)
- [ ]  Actions bar - restart button(Task run)
- [ ] NameTeam (Onboard)
- [ ] Cloud Hooks (team settings )
- [ ] Flow Concurrency (team settings) 
- [ ] Flow Groups (team settings)
- [ ] Add kv button (KV)
- [ ] Invite members button (Members )
- [ ] Create projects (Team settings)
- [ ] Add service account (team settings)
- [ ] Task concurrency (team settings)
- [ ] Update or add payment button (team settings/account)
- [ ] Clear data button (team settings/account)
- [ ] Edit role button (Members)

**Comment by zangell44** [comment]
I'll grab all items for Flows/Tasks/Flowruns/taskruns to start, will update this thread as I test

**Comment by zhen0** [comment]
Members page 
- we should hide 'License Administrator' as a role option if the current user is not a license administrator (This may actually have been handled and reset because of my merge to dev but noting here to make sure we address it.)
- Error handling needs improving in case a user tries to assign a custom role they do not have permissions to assign
- Check if user has read:user permission and adjust subtitle/show alert if not 

Account Page
- Cancel plan button should only show if a user has delete and create license permissions

**Comment by ThatGalNatalie** [comment]
Other places that still need to be converted: 

- [ ] the flow run tutorial still has a check for read only users
- [ ] the interactive api still has a check for read only users
- [ ] and the change state mixin is still disabled for read only users
