### ISSUE TITLE
Starting prefect server without internet connection

### ISSUE THREAD

**Issue by bralbral** [PrefectHQ/ui#91]
## Description

The **prefect ui** docker image has links to fonts from the internet, and if you start the server without internet connection, the UI will be corrupted.

![image](https://user-images.githubusercontent.com/54455457/89741925-04e49a80-da9e-11ea-866a-ea36d2695e41.png)

Solution: download the fonts manually and copy them to the container. Tested on version 0.12.6
[https://easyupload.io/ofkue2](url)

**Comment by gabrielcalderon** [comment]
I'm having the same issue. Currently there's no way to run PrefectHQ/ui in an airgapped system.

The ui resource is requesting Javascript libraries and Fonts from the internet which are not available on private/corporate networks.

**Comment by gabrielcalderon** [comment]
@znicholasbrown Any thoughts on this use case?

**Comment by znicholasbrown** [comment]
Hi @gabrielcalderon - sorry for the slow reply. This is something we may end up doing but it's not on the immediate roadmap since there's a workaround described above; these dependencies are few enough and change infrequently enough that the setup shouldn't be particularly arduous for someone deploying in an airgapped environment.

**Comment by gabrielcalderon** [comment]
@znicholasbrown I have been working on a PR for getting the Fonts and Icons installed through NPM. The only thing left is the FontAwesome icons. It seems the UI is using the following:

```
https://kit.fontawesome.com/f222ce9ce9.js
```

Is there a way to get the list of Icon packs Prefecthq/ui is using? I can't get them from that URL. I'm going to try with the full-package and see if that covers all the icons left.

**Comment by znicholasbrown** [comment]
Hi @gabrielcalderon - we selectively use Font Awesome 5 icons, which we cherry pick from all but the Duotone libraries. 

There are a few icon packages that would cover it (fortawesome core comes to mind) but installation of that as a node module would most likely require changes to `main.js` to register the package and pull in the new assets; I'm not sure exactly what will be needed there, perhaps just a `.css` and `.js` import but maybe more.

**Comment by gabrielcalderon** [comment]
Correct, the changes will go in main.js before the imports for Vue. That's where I have the changes for the fonts and material icons. I will try the FontAwesome core packages. Thanks!

**Comment by bralbral** [comment]
Good day! Any news on this? Should I wait for a fix?
