### ISSUE TITLE
Team menu is not scrollable 

### ISSUE THREAD

**Issue by ThatGalNatalie** [PrefectHQ/ui#911]
**Why**
As we add on new items to the team menu and the list continues to grow, it's currently hard to navigate without zooming out

**What**
This was viewed at 100% zoom
<img width="481" alt="team-menu" src="https://user-images.githubusercontent.com/40726391/123055354-a3c66c80-d3ba-11eb-8da1-a9d233364c53.png">

As in the picture, Task Concurrency is cut off

**Comment by znicholasbrown** [comment]
#909 should address this :)
