### ISSUE TITLE
BUG: UI fails to start for 0.15.3

### ISSUE THREAD

**Issue by saurabh-liftoff** [PrefectHQ/ui#968]
**Bug Description**
When running `prefect server start` command, the docker logs for UI shows this error:
`/start_server.sh: line 11: syntax error: unexpected end of file` and the UI fails to start correctly and is not reachable from http://localhost:8080/

**Steps To Reproduce**
1. pip install prefect
2. prefect backend server
3. prefect server start
4. Check docker container logs for UI

**Browsers Tested:**
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**
Downgrading prefect to 0.15.2 works.

**Comment by zhen0** [comment]
Since we're now on 15.6 I'm going to close this issue.  Please let us know if you see any issues starting the UI again.
