### ISSUE TITLE
Clicking "Show advanced run configuration" in Prefect UI erases RunConfig.host_config

### ISSUE THREAD

**Issue by AlexanderVanEck** [PrefectHQ/ui#977]
## Description

A flow with `run_config=DockerRun(host_config={'network_mode': 'host'})` will have it's host_config overwritten if 'Show advanced run configuration' is clicked in the Prefect UI > Flow > Run.

## Expected Behavior

1. Either host_config should show for Docker run configurations in Prefect UI > Flow > Run
or
2. host_config should not be erased.

## Reproduction

```
with Flow(
    'dummy-flow',
    run_config=DockerRun(
        image='busybox',
        host_config={
            'network_mode': 'host',
        },
    ),
```

1. Register this flow
2. Go to flow > Run
3. Click 'Show advanced run configuration', don't change anything.
4. Click run.
5. See that resulting DockerRun on DockerAgent does not honor network_mode host. (possible to inspect by hacking the agent code before starting, f.e. adding a few print statements to https://github.com/PrefectHQ/prefect/blob/master/src/prefect/agent/docker/agent.py#L412)

## Environment

```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__SERVER__HOST",
    "PREFECT__BACKEND"
  ],
  "system_information": {
    "platform": "Linux-5.4.0-80-generic-x86_64-with-debian-bullseye-sid",
    "prefect_backend": "server",
    "prefect_version": "0.15.3",
    "python_version": "3.6.13"
  }
}
```

**Comment by znicholasbrown** [comment]
Transferred this to the UI repo since this seems like a UI-only bug

**Comment by AlexanderVanEck** [comment]
This is probably caused because the flow was registered with `0.15.3` but the server UI is actually `0.14.2`

**Comment by znicholasbrown** [comment]
Yeah I think that's a good warning - we can add a banner or toast message for that 👍🏻

**Comment by AlexanderVanEck** [comment]
Just upgraded to `0.15.3`, there is no host_config box on the Run page and thus I suspect that the issue stands as is. :)

**Comment by AlexanderVanEck** [comment]
Can confirm that with `0.15.3` this bug is present. The host_config is erased when Advanced settings are viewed.

@znicholasbrown How does it usually work to resolve something like this? As it stands it makes certain flows we'd like to use soft-lock and never complete.

**Comment by znicholasbrown** [comment]
#988 should resolve the issue @AlexanderVanEck

**Comment by madkinsz** [comment]
@znicholasbrown should I be tagging someone on run config changes? Is there a UI change we can make that will not delete run config fields it doesn't know about?

**Comment by znicholasbrown** [comment]
You can tag me for now - it's really straightforward to add new fields; we can look into that but the trouble comes because we're doing such heavy manipulation of that nested config that means the UI doesn't really know what to do with those and wouldn't have a place to display them; if you feel strongly about it it's worth opening a ticket

**Comment by AlexanderVanEck** [comment]
@znicholasbrown Thank you for the quick response on this. :) This will help out a lot!

Would you know when a new patch would be created for this?

**Comment by znicholasbrown** [comment]
This go out later today 😄

**Comment by AlexanderVanEck** [comment]
> This should go out later today 😄

💪 💪
