### ISSUE TITLE
BUG: UI does not function with an active internet connection

### ISSUE THREAD

**Issue by voidel** [PrefectHQ/ui#990]
Please correct me if I'm wrong, but I recently attempted to raise Prefect in an air-gapped environment and was met with several errors due to lack of internet connection.

I believe this may be related to #91, but it doesn't seem to be resolved as specified by #595 ui/public/index.html still contains references to CDN provided for scripts and it doesn't work.

A few examples:

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED cdn.lr-ingest.io/logger-1.min.js
Failed to load resource: net::ERR_NAME_NOT_RESOLVED js.stripe.com/v3/
```

**Comment by znicholasbrown** [comment]
Hi @voidel - can you describe the issue you're having? Those are expected to fail without an active internet connection but the UI should still function without them

**Comment by voidel** [comment]
Thanks for the reply - that's interesting, I have quite a few errors on the UI and I thought that might be something to do with it.

I will debug the rest of them, thanks.
