### ISSUE TITLE
Agents page should not sort based on last refresh time

### ISSUE THREAD

**Issue by Audrius-GR** [PrefectHQ/ui#993]
**Why**

Elements staying in the same location on the page is incredibly important, as the person might be reading the element

**What**

As it stands now, it seems the agent panels in the agents page are sorted based on last refresh time, causing the elements to continuously move in the page, making almost impossible to read/check what's happening.

I have brought this up on the support slack channel we have with you guys, and was told that the sorting was changed, but even after having done a hard refresh, I am seeing this continuous movement of elements, making it impossible to actually see what's going on.

**Comment by zhen0** [comment]
Apologies for the slow reply here - I can't recreate this issue but after thinking on it for a while I have a suspicion it might affect only certain agent types.  We are currently sorting on agent IDs which should have resolved this issue but it's possible that might not work for agents that update frequently.  So I can try replicate again - can you give any more information about the type of agents you are using (my guess is Kubernetes)?

**Comment by rparelius** [comment]
I am experiencing this as well, my agents are local

**Comment by zhen0** [comment]
Thanks @rparelius - can you give any more info?  Do your agents have names?  Have you stopped and started them at all?
