### ISSUE TITLE
Free Tier Users Have Options to Create Service Account Keys with Restricted Permissions

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/ui#998]
**What**

Free tier users see `Read Only` and `User` Roles when creating Service Account Keys in the UI. They then get an Unauthorized message when they try to do this. Instead, they should not be seeing these roles in the drop down in the UI.

* [ ] Ensure that users only see Roles that have restricted permissions on Enterprise accounts. For accounts without RBAC, they should not see these roles.

**Notes**

![image](https://user-images.githubusercontent.com/32503212/129095989-fa557953-8b18-4c4b-b569-4c72fc8167bf.png)
![image](https://user-images.githubusercontent.com/32503212/129095999-abd74bfc-8a8f-4eb7-af3c-cd0d76a6c403.png)

**Comment by sethschori** [comment]
Thanks for opening this bug report @kvnkho!

**Comment by zhen0** [comment]
Closed by #1001
